import React, { useState, useEffect } from 'react';
import { 
  Lock, 
  Key, 
  Server, 
  User, 
  Shield, 
  FileKey, 
  ArrowRight, 
  Clock, 
  CheckCircle,
  AlertTriangle,
  Database,
  RefreshCw,
  ChevronRight,
  ChevronLeft,
  Info
} from 'lucide-react';

// --- Data & Content ---

const steps = [
  {
    id: 1,
    title: "Step 1: User Logs In (Pre-Auth)",
    action: "User -> KDC",
    shortDesc: "Prove you know the password without sending it.",
    visual: {
      from: 'user',
      to: 'kdc',
      item: 'Encrypted Timestamp',
      color: 'bg-blue-500'
    },
    details: (
      <div className="space-y-4">
        <p>The goal is to prove identity <strong>without</strong> ever sending the password across the network where it could be stolen.</p>
        
        <div className="bg-slate-50 p-3 rounded-md border border-slate-200 text-sm">
          <strong className="text-blue-700 block mb-2">Internal Logic:</strong>
          <ul className="list-disc ml-4 space-y-2">
            <li><strong>Hashing:</strong> Your computer takes your password and runs it through a math formula to create a "Secret Key" (User Key).</li>
            <li><strong>The Test:</strong> It takes the current time (e.g., 10:00:00 AM) and <em>encrypts</em> it using that Secret Key.</li>
            <li><strong>The Proof:</strong> This encrypted blob is sent to the KDC. It effectively says: "I can't show you my password, but I can use it to lock this box. If you can unlock it, you know it's me."</li>
          </ul>
        </div>

        <div className="grid grid-cols-2 gap-2 text-xs">
          <div className="bg-green-50 p-2 rounded border border-green-200">
            <span className="font-bold text-green-700">✓ SENT:</span><br/>
            Encrypted Timestamp<br/>Username
          </div>
          <div className="bg-red-50 p-2 rounded border border-red-200">
            <span className="font-bold text-red-700">✗ NOT SENT:</span><br/>
            Plaintext Password<br/>Password Hash
          </div>
        </div>
      </div>
    )
  },
  {
    id: 2,
    title: "Step 2: KDC Issues TGT",
    action: "KDC -> User",
    shortDesc: "Receive the 'Master ID Card' (TGT).",
    visual: {
      from: 'kdc',
      to: 'user',
      item: 'TGT + Session Key',
      color: 'bg-yellow-500'
    },
    details: (
      <div className="space-y-4">
        <p>The KDC looks up your password hash in its database. If it can use that hash to decrypt your timestamp, identity is proven.</p>
        
        <div className="bg-slate-50 p-3 rounded-md border border-slate-200 text-sm space-y-3">
          <strong className="text-blue-700 block">The "Split" Response:</strong>
          
          <div className="bg-white p-2 rounded border border-slate-100 shadow-sm">
             <div className="flex items-center gap-2 mb-1">
                <Key className="w-4 h-4 text-blue-600" />
                <span className="font-bold">Message A: The Login Session Key</span>
             </div>
             <p className="text-xs text-slate-600">
               <strong>Locked with:</strong> Your User Key.<br/>
               <strong>Inside:</strong> A new, temporary "Session Key" generated by the KDC. Your computer decrypts this and keeps it in memory. This replaces your password for future steps.
             </p>
          </div>

          <div className="bg-white p-2 rounded border border-slate-100 shadow-sm">
             <div className="flex items-center gap-2 mb-1">
                <FileKey className="w-4 h-4 text-yellow-600" />
                <span className="font-bold">Message B: The TGT (Ticket Granting Ticket)</span>
             </div>
             <p className="text-xs text-slate-600">
               <strong>Locked with:</strong> The KDC's own <em>krbtgt</em> key.<br/>
               <strong>Inside:</strong> Your username, the <em>same</em> Session Key from Message A, and expiration time.<br/>
               <em className="block mt-1 text-red-500">Note: You cannot decrypt or read this. You just hold it.</em>
             </p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 3,
    title: "Step 3: Request Service Access",
    action: "User -> KDC",
    shortDesc: "Exchange Master ID (TGT) for specific access.",
    visual: {
      from: 'user',
      to: 'kdc',
      item: 'TGT + Authenticator',
      color: 'bg-purple-500'
    },
    details: (
      <div className="space-y-4">
        <p>You want to open a folder on the File Server. You don't send your password. You send the TGT.</p>
        
        <div className="bg-slate-50 p-3 rounded-md border border-slate-200 text-sm">
           <strong className="text-blue-700 block mb-2">Why send two things?</strong>
           <ul className="list-decimal ml-4 space-y-3">
             <li>
               <strong>The TGT:</strong> "This is my Passport." <br/>
               <span className="text-xs text-slate-500">Only the KDC can open this to see who you are.</span>
             </li>
             <li>
               <strong>The Authenticator:</strong> "This is my Face matching the Passport."<br/>
               <span className="text-xs text-slate-500">
                 Logic: You encrypt the current time using the <em>Session Key</em> you got in Step 2. Since only you and the KDC know this Session Key, it proves you are the legitimate owner of the TGT, not a hacker who just stole the ticket file.
               </span>
             </li>
           </ul>
        </div>
      </div>
    )
  },
  {
    id: 4,
    title: "Step 4: KDC Issues Service Ticket",
    action: "KDC -> User",
    shortDesc: "KDC vouches for you to the Server.",
    visual: {
      from: 'kdc',
      to: 'user',
      item: 'Service Ticket',
      color: 'bg-indigo-500'
    },
    details: (
      <div className="space-y-4">
        <p>The KDC validates your TGT and Authenticator. Now it needs to introduce you to the File Server.</p>
        
        <div className="bg-slate-50 p-3 rounded-md border border-slate-200 text-sm">
          <strong className="text-blue-700 block mb-2">Inside the Service Ticket construction:</strong>
          <ol className="list-decimal ml-4 space-y-2">
            <li>The KDC copies your User ID from the TGT.</li>
            <li>It adds your <strong>PAC (Privilege Attribute Certificate)</strong>: This is a list of all groups you belong to (e.g., "Admins", "HR").</li>
            <li>It generates a new <strong>Service Session Key</strong> (for you and the File Server to talk privately).</li>
            <li>It <strong>encrypts the whole thing</strong> using the <em>Server's Key</em>.</li>
          </ol>
        </div>

        <div className="bg-indigo-50 p-2 rounded border border-indigo-200 text-xs flex gap-2">
          <Lock className="w-4 h-4 shrink-0 mt-1" />
          <div>
            <strong>Why use the Server's Key?</strong><br/>
            So the File Server can decrypt this ticket itself without needing to call the KDC. It makes the system faster and more decentralized.
          </div>
        </div>
      </div>
    )
  },
  {
    id: 5,
    title: "Step 5: Access the Server",
    action: "User -> Server",
    shortDesc: "Present the ticket to get in.",
    visual: {
      from: 'user',
      to: 'server',
      item: 'Service Ticket + Timestamp',
      color: 'bg-green-600'
    },
    details: (
      <div className="space-y-4">
        <p>You present the "Service Ticket" directly to the File Server.</p>
        
        <div className="bg-slate-50 p-3 rounded-md border border-slate-200 text-sm">
          <strong className="text-blue-700 block mb-2">The Server's Validation Logic:</strong>
          <ul className="space-y-3">
            <li className="flex gap-2">
              <span className="font-bold text-slate-400">1.</span>
              <span>
                <strong>Decrypt Ticket:</strong> The Server uses its own Secret Key (which it shares with KDC) to open the Service Ticket. It finds your Username and the <em>Service Session Key</em>.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="font-bold text-slate-400">2.</span>
              <span>
                <strong>Decrypt Authenticator:</strong> You also sent a timestamp encrypted with that <em>Service Session Key</em>. The Server uses the key it just found in the ticket to unlock your timestamp.
              </span>
            </li>
            <li className="flex gap-2">
              <span className="font-bold text-slate-400">3.</span>
              <span>
                <strong>Compare:</strong> If the timestamp decrypts correctly and is within 5 minutes of the server's clock &rarr; <strong>Access Granted!</strong>
              </span>
            </li>
          </ul>
        </div>
        <div className="flex items-center justify-center p-3 bg-green-100 rounded text-green-800 font-bold gap-2 text-sm">
          <CheckCircle className="w-5 h-5" />
          You are now logged in.
        </div>
      </div>
    )
  }
];

const keys = [
  { name: "User Key", purpose: "Derived from password. Proves identity to KDC.", owner: "User & KDC" },
  { name: "krbtgt Key", purpose: "The 'Golden Key'. Encrypts/Protects the TGT.", owner: "KDC Only" },
  { name: "Service Key", purpose: "The Server's password hash. Protects Service Ticket.", owner: "KDC & Server" },
  { name: "Session Keys", purpose: "Temporary keys for secure conversation between steps.", owner: "Ephemeral" },
];

const attacks = [
  { name: "Pass-the-Ticket", desc: "Stealing an existing Ticket (TGT or Service) from memory to impersonate a user." },
  { name: "Kerberoasting", desc: "Stealing the Service Ticket to crack the Service Account's password offline." },
  { name: "Golden Ticket", desc: "Forging a TGT using a stolen krbtgt key. Result: Complete domain compromise.", severity: "Critical" },
  { name: "Silver Ticket", desc: "Forging a Service Ticket using a stolen Service key. Result: Compromise of specific server.", severity: "High" },
];

// --- Components ---

const DiagramNode = ({ type, label, icon: Icon, active, isTarget }) => (
  <div className={`relative flex flex-col items-center justify-center p-4 rounded-xl border-2 transition-all duration-500 z-10 w-24 md:w-32 h-24 md:h-32 bg-white
    ${active ? 'border-blue-500 shadow-lg scale-105' : 'border-gray-200 grayscale opacity-70'}
    ${isTarget ? 'ring-4 ring-blue-200' : ''}
  `}>
    <Icon className={`w-8 h-8 md:w-10 md:h-10 mb-2 ${active ? 'text-blue-600' : 'text-gray-400'}`} />
    <span className="text-xs md:text-sm font-bold text-center">{label}</span>
    {/* Key Badges */}
    <div className="absolute -bottom-2 flex gap-1">
      {type === 'user' && <div className="w-3 h-3 rounded-full bg-red-400 border border-white" title="User Key"></div>}
      {type === 'kdc' && (
        <>
          <div className="w-3 h-3 rounded-full bg-red-400 border border-white" title="User Key DB"></div>
          <div className="w-3 h-3 rounded-full bg-yellow-400 border border-white" title="krbtgt Key"></div>
          <div className="w-3 h-3 rounded-full bg-indigo-400 border border-white" title="Service Key DB"></div>
        </>
      )}
      {type === 'server' && <div className="w-3 h-3 rounded-full bg-indigo-400 border border-white" title="Service Key"></div>}
    </div>
  </div>
);

const Packet = ({ show, from, to, color }) => {
  if (!show) return null;

  // Position logic
  const getPos = (type) => {
    switch(type) {
      case 'user': return 'left-[10%]';
      case 'kdc': return 'left-[45%]'; // Center
      case 'server': return 'left-[80%]';
      default: return 'left-0';
    }
  };

  const start = getPos(from);
  const end = getPos(to);
  
  return (
    <div className="absolute top-1/2 -translate-y-1/2 w-full h-12 pointer-events-none">
      <div 
        className={`absolute top-0 w-8 h-8 rounded-full flex items-center justify-center text-white shadow-md transition-all duration-1000 ease-in-out z-20 ${color}`}
        style={{ left: show ? end.replace('left-[','').replace(']','') : start.replace('left-[','').replace(']','') }}
      >
        <Lock className="w-4 h-4" />
      </div>
      {/* Visual Trail */}
      <svg className="absolute top-1/2 -translate-y-1/2 w-full h-2 overflow-visible">
         <line 
           x1={from === 'user' ? '15%' : from === 'kdc' ? '50%' : '85%'} 
           y1="0" 
           x2={to === 'user' ? '15%' : to === 'kdc' ? '50%' : '85%'}  
           y2="0" 
           stroke={color === 'bg-blue-500' ? '#3B82F6' : color === 'bg-yellow-500' ? '#EAB308' : '#6366F1'} 
           strokeWidth="2" 
           strokeDasharray="4"
           className="opacity-50"
         />
      </svg>
    </div>
  );
};

export default function KerberosVisualizer() {
  const [currentStep, setCurrentStep] = useState(0);
  const [activeTab, setActiveTab] = useState('flow'); // flow, keys, attacks
  const [animating, setAnimating] = useState(false);

  // Helper to trigger animation when step changes
  useEffect(() => {
    setAnimating(true);
    const timer = setTimeout(() => setAnimating(false), 1000); // Reset after 1s
    return () => clearTimeout(timer);
  }, [currentStep]);

  const stepData = steps[currentStep];
  
  const handleNext = () => {
    if (currentStep < steps.length - 1) setCurrentStep(c => c + 1);
  };

  const handlePrev = () => {
    if (currentStep > 0) setCurrentStep(c => c - 1);
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans p-4 md:p-8">
      <div className="max-w-6xl mx-auto bg-white shadow-2xl rounded-2xl overflow-hidden border border-slate-200">
        
        {/* Header */}
        <div className="bg-slate-900 text-white p-6 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <Shield className="w-6 h-6 text-yellow-400" />
              Kerberos Protocol Visualizer
            </h1>
            <p className="text-slate-400 text-sm mt-1">Interactive guide based on uploaded documentation</p>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={() => setActiveTab('flow')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'flow' ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}
            >
              Protocol Flow
            </button>
            <button 
              onClick={() => setActiveTab('keys')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'keys' ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}
            >
              Key Reference
            </button>
            <button 
              onClick={() => setActiveTab('attacks')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'attacks' ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}
            >
              Attack Scenarios
            </button>
          </div>
        </div>

        {/* Main Content Area */}
        {activeTab === 'flow' && (
          <div className="grid grid-cols-1 lg:grid-cols-3">
            
            {/* Left: Diagram (Spans 3 cols on mobile, 2 on desktop) */}
            <div className="lg:col-span-2 bg-slate-100 p-8 flex flex-col items-center justify-center border-b lg:border-b-0 lg:border-r border-slate-200 relative min-h-[400px]">
              
              {/* Legend */}
              <div className="absolute top-4 left-4 bg-white/80 backdrop-blur p-2 rounded border border-slate-200 text-xs shadow-sm">
                <div className="font-bold mb-1">Key Legend</div>
                <div className="flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-red-400"></div> User Key</div>
                <div className="flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-yellow-400"></div> krbtgt Key</div>
                <div className="flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-indigo-400"></div> Service Key</div>
              </div>

              {/* Visualization Stage */}
              <div className="w-full relative flex justify-between items-center max-w-lg mx-auto">
                {/* Connecting Lines (Background) */}
                <div className="absolute top-1/2 left-[15%] right-[15%] h-1 bg-slate-300 -translate-y-1/2 z-0"></div>

                {/* Packet Animation */}
                <Packet 
                  show={true}
                  from={animating ? stepData.visual.from : stepData.visual.to} 
                  to={stepData.visual.to} 
                  color={stepData.visual.color} 
                />

                {/* Nodes */}
                <DiagramNode 
                  type="user" 
                  label="User Client" 
                  icon={User} 
                  active={true}
                  isTarget={stepData.visual.to === 'user' || stepData.visual.from === 'user'} 
                />
                
                <DiagramNode 
                  type="kdc" 
                  label="KDC" 
                  icon={Database} 
                  active={true}
                  isTarget={stepData.visual.to === 'kdc' || stepData.visual.from === 'kdc'} 
                />

                <DiagramNode 
                  type="server" 
                  label="File Server" 
                  icon={Server} 
                  active={currentStep >= 4} 
                  isTarget={stepData.visual.to === 'server' || stepData.visual.from === 'server'} 
                />
              </div>

              {/* Visual Context Caption */}
              <div className="mt-12 text-center">
                 <div className={`inline-block px-4 py-2 rounded-full text-white font-medium shadow-md transition-colors duration-500 ${stepData.visual.color}`}>
                    packet contains: {stepData.visual.item}
                 </div>
              </div>

            </div>

            {/* Right: Explanation Panel */}
            <div className="bg-white p-6 flex flex-col h-full overflow-y-auto">
              <div className="flex-1">
                <div className="flex items-center justify-between mb-4">
                  <span className="text-xs font-bold tracking-wider text-slate-500 uppercase">Step {currentStep + 1} of {steps.length}</span>
                  <div className="flex gap-1">
                     <button onClick={handlePrev} disabled={currentStep === 0} className="p-2 hover:bg-slate-100 rounded disabled:opacity-30"><ChevronLeft className="w-4 h-4"/></button>
                     <button onClick={handleNext} disabled={currentStep === steps.length - 1} className="p-2 hover:bg-slate-100 rounded disabled:opacity-30"><ChevronRight className="w-4 h-4"/></button>
                  </div>
                </div>
                
                <h2 className="text-xl font-bold text-slate-800 mb-2">{stepData.title}</h2>
                <p className="text-slate-600 mb-6 italic border-l-4 border-blue-500 pl-3 py-1 bg-blue-50 text-sm">
                  "{stepData.shortDesc}"
                </p>

                <div className="text-slate-700 leading-relaxed text-sm">
                  {stepData.details}
                </div>
              </div>

              {/* Navigation Controls */}
              <div className="mt-8 pt-6 border-t border-slate-100">
                <button 
                  onClick={handleNext}
                  disabled={currentStep === steps.length - 1}
                  className={`w-full py-3 rounded-lg flex items-center justify-center gap-2 font-bold transition-all
                    ${currentStep === steps.length - 1 
                      ? 'bg-green-600 text-white cursor-default' 
                      : 'bg-blue-600 hover:bg-blue-700 text-white shadow-lg hover:shadow-xl'
                    }`}
                >
                  {currentStep === steps.length - 1 ? (
                    <>Protocol Complete <CheckCircle className="w-5 h-5" /></>
                  ) : (
                    <>Next Step <ArrowRight className="w-5 h-5" /></>
                  )}
                </button>
                {currentStep === steps.length - 1 && (
                  <button onClick={() => setCurrentStep(0)} className="w-full mt-2 text-slate-500 text-sm hover:text-blue-600 flex items-center justify-center gap-1">
                    <RefreshCw className="w-3 h-3"/> Replay
                  </button>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Keys Tab */}
        {activeTab === 'keys' && (
          <div className="p-8">
            <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 text-slate-800">
              <Key className="w-6 h-6 text-blue-600" /> Key Usage Reference
            </h2>
            <div className="grid gap-4 md:grid-cols-2">
              {keys.map((k, i) => (
                <div key={i} className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                  <div className="flex justify-between items-start mb-2">
                    <h3 className="font-bold text-lg text-slate-900">{k.name}</h3>
                    <span className="text-xs bg-slate-100 px-2 py-1 rounded text-slate-600 font-mono">
                      Held by: {k.owner}
                    </span>
                  </div>
                  <p className="text-slate-600">{k.purpose}</p>
                </div>
              ))}
            </div>
            <div className="mt-8 bg-blue-50 p-6 rounded-xl border border-blue-100 text-blue-800">
              <h3 className="font-bold mb-2 flex items-center gap-2"><Lock className="w-4 h-4"/> Memory Aid</h3>
              <p>Remember that the KDC (Key Distribution Center) acts as the trusted third party. It holds the "Master Copies" of both the User's key (password hash) and the Server's key.</p>
            </div>
          </div>
        )}

        {/* Attacks Tab */}
        {activeTab === 'attacks' && (
          <div className="p-8">
             <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 text-slate-800">
              <AlertTriangle className="w-6 h-6 text-red-600" /> Common Attacks
            </h2>
            <div className="space-y-4">
              {attacks.map((attack, i) => (
                <div key={i} className="flex gap-4 p-4 bg-white border border-slate-200 rounded-xl shadow-sm hover:border-red-200 transition-colors group">
                  <div className="hidden md:flex items-center justify-center w-12 h-12 rounded-full bg-red-100 text-red-600 shrink-0 group-hover:bg-red-600 group-hover:text-white transition-colors">
                    <AlertTriangle className="w-6 h-6" />
                  </div>
                  <div>
                    <div className="flex items-center gap-3 mb-1">
                      <h3 className="font-bold text-lg text-slate-900">{attack.name}</h3>
                      {attack.severity && (
                        <span className={`text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded ${attack.severity === 'Critical' ? 'bg-red-600 text-white' : 'bg-orange-500 text-white'}`}>
                          {attack.severity}
                        </span>
                      )}
                    </div>
                    <p className="text-slate-600">{attack.desc}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-8 p-6 bg-slate-100 rounded-xl border border-slate-200">
               <h4 className="font-bold text-slate-800 mb-2">Why do these work?</h4>
               <p className="text-sm text-slate-600">Kerberos relies heavily on the secrecy of the keys. If an attacker gains local administrator access to a machine, they can often extract tickets or keys from memory (LSASS process), allowing them to impersonate users or forge tickets without knowing the actual passwords.</p>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}